### PR TITLE
Create jump-smiles README

### PR DESCRIPTION
**Pull request by shntnu**
I used https://til.simonwillison.net/llms/docs-from-tests

### CODE REVIEW

**Comment by shntnu** [comment]
@srijitseal -- @jessica-ewald will be reviewing this PR for it's correctness, by way of using the standardizer, but please review the best practices and standardization methods sections to verify it is all correct. Note that this was auto-generated by Claude based on the code, so there will be errors.

**Comment by jessica-ewald** [comment]
I've verified that when following the steps in the Readme, the code in this pull request works. 

The documentation is helpful, but might be overly verbose with some redundant sections - suggest:

1 - removing the Common Issues and Solutions section 
2 - move the recommendations of when to use jump_canonical and when to use jump_alternate_1 into the description of those options in the Standardization Methods section, then remove the Best Practices section
3 - remove Augmenting Existing Dataset and Error Handling sections

Once this is done and @srijitseal verifies the correctness, then I think its good to go.

**Comment by shntnu** [comment]
@jessica-ewald Thanks! Done

@srijitseal over to you

**Comment by srijitseal** [comment]
Looks good to me!

**Pull request merged**
